ENV: "development"
PORT: 8000
GRPC_PORT: 8001
API_DOMAIN: http://localhost:8000
WEBSITE_DOMAIN: http://127.0.0.1:5173
GIN_MODE: release
DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
TOKEN:
  PRIVATE_KEY: "abc"
  PUBLIC_KEY: "abc"
  REFRESH_TOKEN_TTL: 604800
  ACCESS_TOKEN_TTL: 3600